### PR TITLE
Issue #229: Updated DOM element matching to allow for "//" urls in images

### LINKED ISSUE #229: setting_file_url links are broken in generated static page
Output links from setting_file_url (such as theme header images) lead with '//' instead of http(s). This breaks in the generated static maintenance page.

### PR DESCRIPTION
**Pull request by Peterburnett**
Closes #229

### CODE REVIEW

File: tests/phpunit/local/controllers/maintenance_static_page_test.php [hunk 1]
```diff
@@ -265,6 +265,8 @@ public function test_is_url() {
         self::assertTrue(maintenance_static_page_io::is_url('https://www.catalyst-au.net/'));
         self::assertFalse(maintenance_static_page_io::is_url('/homepage'));
         self::assertFalse(maintenance_static_page_io::is_url('file://homepage'));
+        self::assertTrue(maintenance_static_page_io::is_url('//www.catalyst-au.net/img/test.jpg'));
```
Comment (brendanheywood) [inline tests/phpunit/local/controllers/maintenance_static_page_test.php:268]: bonus points swap this to a data provider
