### PR TITLE
Fix #314: Switch optional_param starttime to optional_param_array

### LINKED ISSUE #314: Error when creating new planned outage
I'm playing around with your moodle plugin but couldn't get an outage planned.
Everytime I try creating a new planned outage the following error occurs:

This is what is shown in the browser.
`Error: Unsupported operand types: array + string`

The php log shows the following:
```
Apr 12 09:11:05 moodleapp1 php[112134]: Default exception handler: Fehler: Unsupported operand types: array + string Debug:
Apr 12 09:11:05 moodleapp1 php[112134]: Error code: generalexceptionmessage
Apr 12 09:11:05 moodleapp1 php[112134]: * line 72 of /auth/outage/edit.php: TypeError thrown
```

We are using PHP 8.0 with Moodle 3.11 on this instance.

### PR DESCRIPTION
**Pull request by gbarat87**
Fix #314 

When warning duration is set to 0, the form fails the validation and return no data https://github.com/catalyst/moodle-auth_outage/blob/MOODLE_501_STABLE/edit.php#L44 

The params starttime comes back as an array of integer. Hence why the error get trigger.

### CODE REVIEW

File: edit.php [hunk 1]
```diff
@@ -48,7 +48,20 @@
 
 $clone = optional_param('clone', 0, PARAM_INT);
 $edit = optional_param('edit', 0, PARAM_INT);
-$time = optional_param('starttime', 0, PARAM_INT);
+$start = optional_param_array('starttime', [], PARAM_INT);
```
Comment (jwalits) [inline edit.php]: The code looks fine and works fine when the outage is posted. However there is a debugging warning when you create a new outage.

```
optional_param_array() only expects array parameters: starttime
    line 535 of /lib/classes/param.php: call to debugging()
    line 712 of /lib/moodlelib.php: call to core\param->optional_param_array()
    line 51 of /auth/outage/edit.php: call to optional_param_array()
```

The "Create Outage" button passes starttime parameter as a string, however when form is posted the date_time_selector element passes the value as an array

**Review by jwalits — APPROVED** [review]
