### PR TITLE
Fix events that trigger re-enabling maintenance mode

### LINKED ISSUE #172: Some actions trigger re-enabling maintenance mode when outage is active
There are 3 actions found:
* Editing ongoing outage if outage has "Auto start maintenance mode" ticked.
* Deleting future outage if there is an active outage with "Auto start maintenance mode" ticked.
* Creating future outage if there is an active outage with "Auto start maintenance mode" ticked.
* Editing "Allowed IP list" setting if there is an active outage with "Auto start maintenance mode" ticked.

Only the first action is supposed to re-enabling maintenance mode. However, it's better to let user know that the site will be taken back to maintenance mode after saving this changes.

### PR DESCRIPTION
**Pull request by golenkovm**
This PR fixes #172 

* Show notification if user edits ongoing outage.
* Amend redirection url when outage is saved. `#auth_outage_id_'.$id` is not needed. If you create outage that starts now you're got redirected to http://your.moodle.com#auth_outage_id_666.
* Do not call `update_maintenance_later()` if you're deleting future outage or editing "Allowed IP list" setting and there is an ongoing outage.
* Hide "Create outage" button if there is an ongoing outage as it will cause re-enabling maintenance mode for ongoing outage. 
* Fix "Cancel button" on Edit form after it was moved from `definition()` method.

### CODE REVIEW

File: classes/form/outage/edit.php [hunk 1]
```diff
@@ -157,8 +157,22 @@ public function set_data($outage) {
                 'title' => $outage->title,
                 'description' => ['text' => $outage->description, 'format' => '1'],
             ]);
+
+            if (!empty($outage->id) && $outage->autostart && $outage->starttime < time() &&
+                    $outage->stoptime > time()) {
+                $this->_form->addElement('html',
+                    $OUTPUT->notification(get_string('warningreenablemaintenancemode', 'auth_outage'), 'notifywarning'));
```
Comment (brendanheywood) [inline classes/form/outage/edit.php]: if feels wrong to be outputting html as a side effect inside the form set_data, shouldn't this be outside in the code which is calling the form?

File: classes/local/outagelib.php [hunk 2]
```diff
@@ -163,16 +163,25 @@ public static function get_config_defaults() {
 
     /**
      * Executed when outages are modified (created, updated or deleted).
+     *
+     * @param bool $reenablemaint should we re-enable maintenance mode for ongoing outage
```
Comment (brendanheywood) [inline classes/local/outagelib.php]: none of this logic seem right to me.

The outage page contains info, dates, descriptions. If you change the outage then this stuff should change, the static pages should be rebuilt. This feels like a workaround to a deeper problem

Comment (brendanheywood) [reply classes/local/outagelib.php]: ah sorry, this is only the config item

File: classes/form/outage/edit.php (hunk 1 above)
Comment (brendanheywood) [reply classes/form/outage/edit.php]: actually I think this warning should be in the form definition as a static html form element

File: classes/local/outagelib.php (hunk 2 above)
Comment (golenkovm) [reply classes/local/outagelib.php]: Yep, but should we re-enable maintenance mode? We can re-build static page and leave maintenance mode disabled. I don't think that admins expect maintenance to be enabled if they just extend outage period or add new IP onto white list

File: views/manage.php [hunk 3]
```diff
@@ -47,9 +48,12 @@
         $table->finish_output();
         ?>
     <?php endif; ?>
-    <input type="button" class="form-submit"
-           value="<?php echo get_string('outagecreate', 'auth_outage'); ?>"
-           onclick="location.href='<?php echo $urlnew; ?>';"/>
+    <?php $outage = outagedb::get_ongoing(); ?>
+    <?php if (is_null($outage)): ?>
+        <input type="button" class="form-submit"
```
Comment (brendanheywood) [inline views/manage.php]: why is this custom html? Why not just:

echo $OUTPUT->single_button(
