### PR TITLE
Fix #234 pick up images from inline style background image.

### LINKED ISSUE #234: When prebaking the static theme file, handle redirects
ie if a theme uses a file, the file normally is served as a redirect to s3 signed url. It is very likely this is getting broken somehow.

The symptoms are that this file is not being served using the static file.php, so it ends up going to a real script which then gets diverted to the outage page

### PR DESCRIPTION
**Pull request by katerynadegtyariova**
Fix #234 pick up images from inline style background image.
Created unit test that generates a page and check the background URL in the inline style.

### CODE REVIEW

File: tests/phpunit/local/controllers/maintenance_static_page_test.php [hunk 1]
```diff
@@ -193,6 +193,60 @@ public function test_updatelinkfavicon() {
         self::assertStringContainsString('www.example.com/moodle/auth/outage/file.php?file=', $generated);
     }
 
+
+    /**
+     * Data provider for test_update_inline_background_images
+     * @return array
```
Comment (brendanheywood) [inline tests/phpunit/local/controllers/maintenance_static_page_test.php:199]: This is looking great. A few structural suggestions:

1) you are asserting that an update happens, but I think it might be better to assert what the end result actually was

2) similar to above, you are asserting that a small chunk of inline css is replaced, but it might be more useful and robust to check that a chunk of html is transformed into another chunk of html.

That said both are bonus points and can be worried about later, I think this is good to land (but I haven't actually run it and tested it)

Comment (katerynadegtyariova) [reply tests/phpunit/local/controllers/maintenance_static_page_test.php:199]: Thanks Brendan.
I will do the changes you suggested in the next version of the patch.
Please let me know when you try running the unit tests.

File: classes/local/controllers/maintenance_static_page_generator.php [hunk 2]
```diff
@@ -218,6 +240,31 @@ private function update_images() {
...
+     * Fetch and fixes all inline background images.
+     */
+    private function update_inline_background_images() {
+        global $CFG;
+        $xpath = new \DOMXPath($this->dom);
+        $elements = $xpath->query("//*[@style]");
+
+        foreach ($elements as $element) {
+            $style = $element->getAttribute("style");
+            $matches = $this->get_url_from_inline_style($style, $pattern);
```
Comment (brendanheywood) [inline classes/local/controllers/maintenance_static_page_generator.php]: Where does $pattern from in this function? It looks undeclared

File: tests/phpunit/local/controllers/maintenance_static_page_test.php [hunk 3]
```diff
@@ -193,6 +193,60 @@ public function test_updatelinkfavicon() {
...
+            '<html><head><title>Title</title></head>'.
+            '<body><div style="'.$stylecontent.'">Content</div></body></html>';
+
+        // Temporarily disable debugging to prevent errors because file does not exist
+        $debuglevel = $CFG->debug;
+        $CFG->debug = '';
+        $generated = $this->generated_page_html($html);
+        // Restore debugging level
+        $CFG->debug = $debuglevel;
+        $matches = $generator->get_url_from_inline_style($stylecontent, $pattern);
```
Comment (brendanheywood) [inline tests/phpunit/local/controllers/maintenance_static_page_test.php]: same here

File: classes/local/controllers/maintenance_static_page_generator.php (hunk 2 above)
Comment (brendanheywood) [reply classes/local/controllers/maintenance_static_page_generator.php]: ah its a reference, maybe it would be clearer if instead of passing this in by reference and populating it, why not just make that part of the return value? Or given that it is static data you could make it a class level constant?

**Comment by katerynadegtyariova** [comment]
Fixed the issue by moving pattern to class constant
